### ISSUE TITLE
元数据格式与 IPFS 存储方式

### ISSUE THREAD

**Issue by linonetwo** [exxhentai/rehentai#2]
我观察了一下元数据，爬取的相比导出的（中文本子元数据）还是少一些字段，我们还得做一些融合和去重。

https://github.com/Tlaster/exback
```typescript
interface Root {
  id: string;
  title: string;
  type: string;
  /** 因为 eh 上的画廊是 immutable 的，上传之后不可修改，所以上传时间就是修改时间（这很 ipfs ）
  time: string;
  /** https://exhentai.org/g/xxx 这样的，这个字段得改变了 */ 
  link: string;
  /** 缩略图，这一项以后就换成 ipfs hash */
  img: string;
  uploader: string;
  tags: Tag[];
}

interface Tag {
  /** female / female / parody / group / artist / language ... */
  name: string;
  /** ["anal","cosplaying","dark sclera","double penetration","fox girl","furry","nakadashi"] */
  values: string[];
}
```

希望我们的元数据库里， `link` 字段能指向一个 IPFS 文件夹（即 MerkleDAG 节点，看起来是一个和文件 hash 一样的 IPFS hash ，但是通过 IPFS 网关可以看到它打开来是一个文件夹，里面有很多个指向子文件夹或者文件的 IPFS hash ）

exhentai_gallery.sql
```sql
CREATE TABLE `exhentai_gallery` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `gid` int(11) NOT NULL,
  `token` varchar(16) NOT NULL,
  `title` varchar(256) DEFAULT NULL,
  `title_jpn` varchar(256) DEFAULT NULL,
  `category` varchar(16) DEFAULT NULL,
  `thumb` varchar(128) DEFAULT NULL,
  `rating` float DEFAULT NULL,
  `rating_count` int(11) DEFAULT NULL,
  `favorited_count` int(11) DEFAULT NULL,
  `uploader` varchar(24) DEFAULT NULL,
  `upload_time` bigint(20) DEFAULT NULL,
  `file_count` smallint(6) DEFAULT NULL,
  `file_size` bigint(20) DEFAULT NULL,
  `archive_key` varchar(64) DEFAULT NULL,
  `tags` text DEFAULT NULL,
  `last_update` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `exhentaigallery_gid` (`gid`),
  KEY `upload_time` (`upload_time`)
) ENGINE=InnoDB AUTO_INCREMENT=227896 DEFAULT CHARSET=utf8mb4;
```

这个应该是比较齐全的元信息字段，我猜测就是 MainDB 那个：

![E-Hentai Infrastructure](https://ehwiki.org/images/a/ac/E-Hentai_Infrastructure.png)

其中 tags 就是上面的 JSON 序列化之后的吧，我的疑惑是这样是不是不方便搜索？

**Comment by r1235613** [comment]
我研究一下IPFS和Pyhton，看能不能在整理元數據時就兜在一起

**Comment by linonetwo** [comment]
涉及 IPFS 的后端应该用 go 来写，因为 IPFS 稳定的库只有 go 和 js 的……
所以应该是 go server 来把图片添加到 ipfs 上并合并成一个 ipfs 文件夹。

Python 我们就直接存元信息就好，go server 通过 REST 往元信息数据库里加 hash 就好了。

**Comment by GooeyNyan** [comment]
> 其中 tags 就是上面的 JSON 序列化之后的吧，我的疑惑是这样是不是不方便搜索？

那不止是不方便搜索的吧，而且很慢吧。

就以认知来说，`tag` 属于经常搜索的字段，但是这边连个索引都没建。

要么是这份 SQL 漏了什么信息，要么是我们现在手上的信息还是太少了，感觉不是在这个表做 tag 的查询的。

**Comment by linonetwo** [comment]
@r1235613  你设计一下吧，你是用 flask 写 API ，加上什么数据库来着？除了 PostgreSQL 还有啥别的选择吗？

**Comment by GooeyNyan** [comment]
> @r1235613 你设计一下吧，你是用 flask 写 API ，加上什么数据库来着？除了 PostgreSQL 还有啥别的选择吗？

MySQL PostgreSQL MongoDB，目前 70W 的数据都不算大的。

**Comment by r1235613** [comment]
我目前偏向MariaDB，但是對Pyhton的模型來說，DB差異不大，看看其他語言有沒有好用的DB，取個交集讓大家方便做事。
MongoDB目前密笈在台灣，手邊沒有書憑印象如果要架設有點不靠譜，但是操作還是沒問題的。
另外管DB有人嗎？雖然我會管Linux、DB但畢竟不是專家。
我支援的DB：https://docs.sqlalchemy.org/en/13/core/engines.html#database-urls  + MongoDB

**Comment by kamira** [comment]
儲存若不常變更的話，我倒是比較推薦可分散的elasticsearch

**Comment by r1235613** [comment]
> 就以认知来说，tag 属于经常搜索的字段，但是这边连个索引都没建。
>要么是这份 SQL 漏了什么信息，要么是我们现在手上的信息还是太少了，感觉不是在这个表做 tag 的查询的。

在我看的到書中，Tag似乎都是建多對多去處理……到這規模的東西就覺得我能力根本是渣

**Comment by GooeyNyan** [comment]
> > 就以认知来说，tag 属于经常搜索的字段，但是这边连个索引都没建。
> > 要么是这份 SQL 漏了什么信息，要么是我们现在手上的信息还是太少了，感觉不是在这个表做 tag 的查询的。
> 
> 在我看的到書中，Tag似乎都是建多對多去處理……到這規模的東西就覺得我能力根本是渣

肯定是多对多的，起码目前看起来70W元数据的规模也不算大。

**Comment by misaka10055** [comment]
如果用flask写我可以来帮忙。我对flask还算比较熟悉。

就搜索来说，多对多的表肯定是要建的，但是我觉得不用过度追求性能。总共的数据条目数量也就60W差不多（分表建索引后也就顶多几百万吧），这点数据处理起来还是不困难的。

// 抱歉之前没看到已经有可用的VPS了

**Comment by GooeyNyan** [comment]
> 如果用flask写我可以来帮忙。我对flask还算比较熟悉。
> 
> 就搜索来说，多对多的表肯定是要建的，但是我觉得不用过度追求性能。总共的数据条目数量也就60W差不多（分表建索引后也就顶多几百万吧），这点数据处理起来还是不困难的。
> 
> // 抱歉之前没看到已经有可用的VPS了

好啊好啊，r1235613 目前在做后端 API 这块，可以联系他。

平时一般在 [discord](https://discordapp.com/invite/asvGaZ) 上活动。

**Comment by linonetwo** [comment]
@zjdavid2  已邀请你，你去 discord 私信 @r1235613  协调一下吧

**Comment by r1235613** [comment]
@zjdavid2 來的正好，來幫我決定要用SQL還是NoSQL

**Comment by misaka10055** [comment]
> @zjdavid2 來的正好，來幫我決定要用SQL還是NoSQL

SQL 我在一些项目里用过，比较熟悉。如果tag 分出一个表，gid/其他信息分出一个表，然后建一个中间表做索引，目前性能应该是没问题的（毕竟数据量不是太大）。

NoSQL 我只拿它做了个小型聊天工具。我感觉对于大数据量来说NoSQL是最好的选择。如果我们要做comment系统的话那么数据量可能会变得很大，所以我觉得NoSQL长远来看会更好。

**Comment by misaka10055** [comment]
> @zjdavid2 來的正好，來幫我決定要用SQL還是NoSQL

话说flask这块开始做了吗？如果还没的话我今天有时间可以把基础的框架先弄起来。

**Comment by r1235613** [comment]
@zjdavid2 不如先決定好API要開哪些吧，移步到[另一個專案](https://github.com/exxhentai/flask)
我也認為No-SQL好，本專案應該不要求數據高度一致性，下午有期末考，晚上再來處理

**Comment by misaka10055** [comment]
> @zjdavid2 不如先決定好API要開哪些吧，移步到[另一個專案](https://github.com/exxhentai/flask)
> 我也認為No-SQL好，本專案應該不要求數據高度一致性，下午有期末考，晚上再來處理

好的，我中午整理个API List出来。
祝期末考顺利。

**Comment by HTYISABUG** [comment]
只要主伺服器容量夠大，IPFS 在上傳不會有問題，但是下載的問題很大
經過測試，任意未與內容伺服器連結的 IPFS client ，若要取得內容所需的時間極長
但如果有通過 `ipfs swarm connect <address>` 對 node 作連結可以極大的縮短取得時間
因此若以 IPFS 為儲存媒介，我們會需要很多類似 H@H 的 node 來分散內容
同時後端伺服器也會需要管理與 node 的連結，以加快讀取速度

補充：
聽說 IPFS node 會被動接收一些碎片？
那麼 node 大概是初期需要至少掛一段時間？

**Comment by linonetwo** [comment]
IPFS 节点不会主动下载别人的数据，只是在帮忙更新 DHT 而已，会义务帮别的节点寻址。

我试试一开始就把服务器的地址加到 swarm 里面：

```
new Ipfs({
    repo: repoPath,
    config: {
      Addresses: {
        API: '/ip4/127.0.0.1/tcp/0',
        Swarm: ['/ip4/0.0.0.0/tcp/0', 'server's multi address'],
        Gateway: '/ip4/0.0.0.0/tcp/0',
      },
    },
  })
```

前端界面加载到用户浏览器之后，再找 go server 取一下当前做种节点的列表，也添加进去。

**Comment by HTYISABUG** [comment]
> IPFS 节点不会主动下载别人的数据，只是在帮忙更新 DHT 而已，会义务帮别的节点寻址。
> 
> 我试试一开始就把服务器的地址加到 swarm 里面：
> 
> ```
> new Ipfs({
>     repo: repoPath,
>     config: {
>       Addresses: {
>         API: '/ip4/127.0.0.1/tcp/0',
>         Swarm: ['/ip4/0.0.0.0/tcp/0', 'server's multi address'],
>         Gateway: '/ip4/0.0.0.0/tcp/0',
>       },
>     },
>   })
> ```
> 
> 前端界面加载到用户浏览器之后，再找 go server 取一下当前做种节点的列表，也添加进去。

知道了，go server 這邊會再維護節點列表

**Comment by 976047167** [comment]
元数据可不可以用ipfs-pubsb功能来进行储存，看到有人基于这个功能实现了点对点的聊天。目前有基于这个功能的数据库orbit-db

**Comment by linonetwo** [comment]
元数据相关已转移到 https://github.com/exxhentai/flask/issues/8 讨论
内容服务器在 https://github.com/exxhentai/rehentai-content-server 已有第一版。
